CREATE TABLE `activity_log` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`idempotency_key` text,
	`occurred_at` integer NOT NULL,
	`actor` text NOT NULL,
	`contact_type` text NOT NULL,
	`supplier_id` integer,
	`client_id` integer,
	`contact_name` text NOT NULL,
	`action_type` text NOT NULL,
	`old_status` text,
	`new_status` text,
	`response_text` text,
	`next_action` text,
	`next_action_at` integer,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `activity_log_idempotency_key_unique` ON `activity_log` (`idempotency_key`);--> statement-breakpoint
CREATE INDEX `activity_log_supplier_idx` ON `activity_log` (`supplier_id`);--> statement-breakpoint
CREATE INDEX `activity_log_client_idx` ON `activity_log` (`client_id`);--> statement-breakpoint
CREATE INDEX `activity_log_occurred_at_idx` ON `activity_log` (`occurred_at`);--> statement-breakpoint
CREATE TABLE `client_basket_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`client_id` integer NOT NULL,
	`product` text NOT NULL,
	`brand` text,
	`sku` text,
	`packaging` text,
	`canister_quantity` integer,
	`liters_per_month` real,
	`purchase_frequency` text,
	`current_price` text,
	`delivery` text,
	`ready_to_test_alternative` text DEFAULT 'unknown' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `client_basket_items_client_idx` ON `client_basket_items` (`client_id`);--> statement-breakpoint
CREATE TABLE `clients` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`two_gis_firm_id` text NOT NULL,
	`rank` integer NOT NULL,
	`priority` text NOT NULL,
	`priority_reason` text,
	`confidence_score` integer,
	`confidence_reason` text,
	`contact_quality` text,
	`name` text NOT NULL,
	`category` text,
	`address` text,
	`whatsapp` text,
	`whatsapp_normalized` text,
	`phone` text,
	`email` text,
	`instagram` text,
	`telegram` text,
	`vk` text,
	`website` text,
	`two_gis_url` text NOT NULL,
	`source_activity` text,
	`probable_products` text,
	`source_purchase_frequency` text,
	`best_first_question` text,
	`source_current_basket` text,
	`source_current_supplier` text,
	`source_purchase_volume` text,
	`source_decision_maker` text,
	`scrape_date` text,
	`last_checked_at` text,
	`scrape_method` text,
	`needs_manual_review` integer DEFAULT false NOT NULL,
	`manual_review_reason` text,
	`auto_found_fields` text,
	`duplicate_group` text,
	`source_url` text,
	`raw_data` text,
	`source_imported_at` integer NOT NULL,
	`owner` text DEFAULT 'Ерасыл' NOT NULL,
	`status` text DEFAULT 'не активирован' NOT NULL,
	`current_supplier` text,
	`problem` text,
	`next_contact_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `clients_two_gis_firm_id_unique` ON `clients` (`two_gis_firm_id`);--> statement-breakpoint
CREATE INDEX `clients_rank_idx` ON `clients` (`rank`);--> statement-breakpoint
CREATE INDEX `clients_status_idx` ON `clients` (`status`);--> statement-breakpoint
CREATE INDEX `clients_priority_idx` ON `clients` (`priority`);--> statement-breakpoint
CREATE TABLE `import_runs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`file_name` text NOT NULL,
	`file_hash` text NOT NULL,
	`status` text DEFAULT 'running' NOT NULL,
	`suppliers_created` integer DEFAULT 0 NOT NULL,
	`suppliers_updated` integer DEFAULT 0 NOT NULL,
	`suppliers_unchanged` integer DEFAULT 0 NOT NULL,
	`clients_created` integer DEFAULT 0 NOT NULL,
	`clients_updated` integer DEFAULT 0 NOT NULL,
	`clients_unchanged` integer DEFAULT 0 NOT NULL,
	`errors_json` text,
	`started_at` integer NOT NULL,
	`finished_at` integer
);
--> statement-breakpoint
CREATE INDEX `import_runs_started_at_idx` ON `import_runs` (`started_at`);--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`external_key` text NOT NULL,
	`rank` integer NOT NULL,
	`priority` text NOT NULL,
	`priority_reason` text,
	`confidence_score` integer,
	`confidence_reason` text,
	`contact_quality` text,
	`name` text NOT NULL,
	`category` text,
	`country` text,
	`city` text,
	`website` text,
	`whatsapp` text,
	`whatsapp_normalized` text,
	`phone` text,
	`email` text,
	`instagram` text,
	`telegram` text,
	`vk` text,
	`partnership_program` text,
	`partnership_url` text,
	`source_delivery` text,
	`source_moq` text,
	`source_sds` text,
	`source_agency_scheme` text,
	`source_client_protection` text,
	`source_commission` text,
	`source_repeat_commission` text,
	`potential_margin` text,
	`weaknesses` text,
	`scrape_date` text,
	`last_checked_at` text,
	`scrape_method` text,
	`needs_manual_review` integer DEFAULT false NOT NULL,
	`manual_review_reason` text,
	`auto_found_fields` text,
	`source_url` text,
	`raw_data` text,
	`source_imported_at` integer NOT NULL,
	`owner` text DEFAULT 'Димаш' NOT NULL,
	`status` text DEFAULT 'не начато' NOT NULL,
	`last_contact_at` integer,
	`next_action_at` integer,
	`original_response` text,
	`internal_comment` text,
	`next_action` text,
	`has_shymkent_representative` text DEFAULT 'unknown' NOT NULL,
	`decision_maker` text,
	`agency_format_possible` text DEFAULT 'unknown' NOT NULL,
	`no_stock_purchase_required` text DEFAULT 'unknown' NOT NULL,
	`supplier_invoices_client` text DEFAULT 'unknown' NOT NULL,
	`supplier_delivers_client` text DEFAULT 'unknown' NOT NULL,
	`commission_first_order` text DEFAULT 'unknown' NOT NULL,
	`commission_repeat_orders` text DEFAULT 'unknown' NOT NULL,
	`client_protection_confirmed` text DEFAULT 'unknown' NOT NULL,
	`client_protection_mechanism` text,
	`client_protection_term` text,
	`qualified_moq` text,
	`samples_available` text DEFAULT 'unknown' NOT NULL,
	`samples_comment` text,
	`price_received` text DEFAULT 'unknown' NOT NULL,
	`documents_sds_received` text DEFAULT 'unknown' NOT NULL,
	`logistics_comment` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `suppliers_external_key_unique` ON `suppliers` (`external_key`);--> statement-breakpoint
CREATE INDEX `suppliers_rank_idx` ON `suppliers` (`rank`);--> statement-breakpoint
CREATE INDEX `suppliers_status_idx` ON `suppliers` (`status`);--> statement-breakpoint
CREATE INDEX `suppliers_priority_idx` ON `suppliers` (`priority`);--> statement-breakpoint
CREATE INDEX `suppliers_next_action_idx` ON `suppliers` (`next_action_at`);